[deps]
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
RetrievalToolbox = "46b81e12-0ded-426f-b207-2eae42eca022"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[sources]
RetrievalToolbox = {rev = "main", url = "https://github.com/US-GHG-Center/RetrievalToolbox.jl"}
